sudo: false

language: ruby

before_install:
  - gem update --system
  - gem install bundler

after_success:
  # - coveralls
  - bundle exec danger

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0

matrix:
  fast_finish: true

  include:
    - rvm: 2.3.8
    - rvm: ruby-head
    - rvm: jruby-head

  allow_failures:
    - rvm: 2.3.8
    - rvm: ruby-head
    - rvm: jruby-head
