language: ruby

before_install:
  - gem install bundler

after_success:
  - bundle exec danger

rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0

matrix:
  fast_finish: true

  include:
    - rvm: 2.5.8
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby-head

  allow_failures:
    - rvm: 2.5.8
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby-head
